### PR TITLE
[Surefire-1516] Improve IPC performace with Sockets

### PR DESCRIPTION
**Pull request by Col-E**
## Reasoning

When using the following configuration as opposed to the default values there is a noticeable increase in the required time to perform `mvn test`

| Setting    | Value |
|------------|-------|
| forkCount  | 1     |
| reuseForks | false |

This PR looks to cut down on this increased time. Through some analysis we came upon the realization that a significant delay is introduced by the inter-process communication between a `ForkStarter` and `ForkedBooter`. The blocking of process input/output streams is the culprit as verified by this in-depth response to a StackOverflow post  ["Blocking on stdin makes Java processes take 350ms or more to exit"](https://stackoverflow.com/a/48979347/)

So in order to circumvent this performance hit we looked into how to alternate forms of IPC and settled on Sockets. Details on the changes and the the improvement on performance are below.

### ForkStarter

A `ServerSocket` is started on an arbitrary open port in `RunResult fork(...)`. This port is passed to child processes _(`ForkedBooter)_ by passing an additional argument to the command-line arguments of the booter. Additionally in order to efficiently pass the name of the test class to the booter the test class name is passed via the command-line arguments. Because the test class name is only required in our use case for this configuration it should be optional in the command-line arguments.

This is a problem because there is already an optional parameter for passing the system properties via a file and the handling of this optional value in the booter assumes there is only one optional argument... but now we have two and now way to differentiate them. Thus we minimally implemented optional argument parsing in `org/apache/maven/surefire/booter/CmdParser` _(See below for more info)_

Continuing on with the socket we started in `ForkStarter` we made a wrapper for `org/apache/maven/shared/utils/cli/Commandline` which allows us to intercept the process's input/output streams with out socket's. This ensures that only _minimal_ changes needed to be made to the `org/apache/maven/surefire/booter/CommandReader` class.

### CommandReader

As mentioned above this class was _minimally_ modified. Due to the widespread usage of this class significant changes are simply not a good idea. 

This class previously handled communication via `new DataInputStream( System.in );`. To allow changing the stream source to a socket's a few non-public design changes were made. The constant static `READER` is now lazily instantiated via `CommandReader getReader( Socket socket )`. The old behavior of `System.in` reading is still present when via `CommandReader getReader()`

### CmdParser

As mentioned above there is now a need for multiple optional arguments. This class is a minimal implementation that adds just what is needed. Indexed args are treated as they were prior, but now if a arg is prefixed with `-` it is interpreted as `-$ARG_NAME:$ARG_VALUE`. Since we control all invocations of the booter we know this format will always be used. 

This class provides a map for indexed arguments and named arguments, and is used in the booter to replace the old and simplistic command-line parsing.

### ForkedBooter

The instantiations of `CommandReader commandReader` and `ForkedChannelEncoder eventChannel` are moved explicitly into the new booter constructor `ForkedBooter( Socket clientSocket )` since they now require the socket's streams. Additionally the new argument for single test class names allows a faster and more simple way to instantiate `Object testSet`

In the `main(String[] args)` method the booter parses the command-line arguments and then connects to the starter's socket. This provides the information necessary to properly invoke `setupBooter`

## Benchmarks

The following table shows the average reduction in execution time of the `test` phase in various projects between the current `3.0.0-M3` release and our fork.

| Project               | Speedup |
|-----------------------|---------|
| Bukkit                | 45.81%  |
| checkstyle            | 26.51%  |
| commons-codec         | 36.88%  |
| commons-compress      | 40.21%  |
| commons-configuration | 30.29%  |
| commons-dbcp          | 9.00%   |
| commons-io            | 25.80%  |
| commons-jxpath        | 40.39%  |
| commons-lang          | 39.72%  |
| commons-math          | 36.06%  |
| commons-net           | 14.98%  |
| commons-validator     | 43.99%  |
| eclipse-collections   | 38.18%  |
| empire-db             | 37.52%  |
| gedcom4j              | 37.73%  |
| google-java-format    | 21.19%  |
| graphhopper           | 36.24%  |
| jfreechart            | 48.28%  |
| joda-time             | 0.70%   |
| la4j                  | 28.58%  |
| Openfire              | 23.37%  |
| retrofit              | 28.03%  |
| scribejava            | 40.80%  |
| truth                 | 36.49%  |
| vectorz               | 45.85%  |
| yamlbeans             | 38.50%  |
| zt-exec               | 17.23%  |

### CODE REVIEW

**Comment by Col-E** [comment]
For reference: [results.xlsx](https://github.com/gmu-swe/maven-surefire/files/3776109/results.xlsx)

**Comment by Tibor17** [comment]
@Col-E What is Standard, Custom and Forkscript in yout charts?

**Comment by Col-E** [comment]
* Standard is 3.0.0-M3
* Custom is our modified version of 3.0.0-M3
* Forkscript is a modification of 2.21 that used a bash script to invoke junit jvms

**Comment by Tibor17** [comment]
Regarding Forkscript, pls see my comment https://github.com/apache/maven-surefire/pull/250#issuecomment-549610683 and the commit https://github.com/apache/maven-surefire/commit/349628f68229fbed19d72fe38fefc481f39387e6 from @jon-bell 

Can you pls repeat the benchmark tests and add the fourth option which would be the commit https://github.com/apache/maven-surefire/commit/349628f68229fbed19d72fe38fefc481f39387e6 on the top of the release 3.0.0-M3 ?
My information from @jon-bell is that his commit has as the same speedup as Forkscript.
We should include these benchmark test results in official Surefire documentation https://maven.apache.org/surefire/maven-surefire-plugin/ because then most of our users will see the benefit of M4 but usually the user does not guess the benefit from having a look into the code or JIRA.

**Comment by jon-bell** [comment]
For what it's worth, the speedup is only visible for configurations with `reuseForks=false`. It is somewhat difficult to rerun this whole experiment, so maybe we should wait until everything is in place for 3.0.0-M4.

**Comment by Tibor17** [comment]
and if you pickup only `EmpireDB`? It has a significant differences between these three options.

**Pull request merged**
